name: petcare
description: PetCare - Love Your Pets Every Day. Track pet health, vaccines, feeding and grooming.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.3
  uuid: ^4.1.0
  in_app_purchase: ^3.2.1
  google_mobile_ads: ^5.3.1
  http: ^1.2.2
  intl: ^0.20.2
  fl_chart: ^0.70.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  image_picker_android: ^0.8.13+19
  image_picker_platform_interface: ^2.11.1
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon_foreground.png
  adaptive_icon_background: "#F5F0FF"
  adaptive_icon_foreground: assets/icon_foreground.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon_foreground.png
