const Map<String, String> appStringsVi = {
  'appName': 'PetCare',
  'appTagline': 'Yêu thương thú cưng mỗi ngày.',
  'splashLoading': 'Đang tải...',

  'navHome': 'Trang chủ',
  'navTips': 'Mẹo hay',
  'navLogs': 'Thống kê',
  'navTimeline': 'Nhật ký',
  'navMore': 'Thêm',
  'navShop': 'Cửa hàng',
  'navSettings': 'Cài đặt',

  'tabPets': 'Thú cưng',
  'tabRoutines': 'Thói quen',
  'tabFamily': 'Gia đình',
  'tabJournals': 'Nhật ký',

  'addPet': 'Thêm thú cưng',
  'editPet': 'Sửa hồ sơ',
  'petProfile': 'Hồ sơ thú cưng',
  'petName': 'Tên thú cưng',
  'species': 'Loài',
  'speciesDog': 'Chó',
  'speciesCat': 'Mèo',
  'speciesOther': 'Khác',
  'breed': 'Giống',
  'birthDate': 'Ngày sinh',
  'furColor': 'Màu lông',
  'gender': 'Giới tính',
  'genderMale': 'Đực',
  'genderFemale': 'Cái',
  'genderUnknown': 'Chưa rõ',
  'changePhoto': 'Đổi ảnh',
  'addPhoto': 'Thêm ảnh',
  'tapToAddPhoto': 'Chạm để thêm ảnh',
  'chooseGallery': 'Chọn từ thư viện',
  'takePhoto': 'Chụp ảnh',
  'todaySummary': 'Hôm nay',
  'summaryFeeding': '{count} bữa ăn',
  'summaryGrooming': '{count} chăm sóc',
  'summaryHealth': '{count} sức khỏe',
  'summaryTotal': '{count} hoạt động',
  'lastCare': 'Chăm sóc gần nhất',
  'myPets': 'Thú cưng của tôi',
  'homeGreeting': 'Chào {name},',
  'homeSubtitlePrefix': 'Hãy chăm sóc ',
  'homeSubtitleHighlight': 'thú cưng xinh yêu!',
  'nutrition': 'Ăn uống',
  'consult': 'Tư vấn',
  'healthCheckup': 'Khám sức khỏe',
  'reminderHealthCheckup': 'Khám sức khỏe',
  'petDetails': 'Chi tiết thú cưng',
  'onboardingHeadlinePart1': 'Giúp',
  'onboardingHeadlineYou': 'bạn',
  'onboardingHeadlinePart2': 'chăm sóc',
  'onboardingHeadlinePet': 'Thú cưng',
  'onboardingCaption': 'Mọi thú cưng đều xứng đáng được yêu thương!',
  'weightLabel': 'Cân nặng',
  'noWeightYet': 'Chưa ghi cân nặng',

  'feeding': 'Ăn uống',
  'vaccine': 'Tiêm phòng',
  'health': 'Sức khỏe',
  'grooming': 'Chăm sóc',
  'statistics': 'Thống kê',
  'weight': 'Cân nặng (kg)',
  'profile': 'Hồ sơ',
  'timeline': 'Nhật ký',

  'feedingTitle': 'Ghi bữa ăn',
  'feedingType': 'Loại thức ăn',
  'feedingDry': 'Thức ăn khô',
  'feedingWet': 'Thức ăn ướt',
  'feedingRaw': 'Thức ăn sống',
  'feedingTreat': 'Snack',
  'feedingHomemade': 'Tự nấu',
  'portion': 'Khẩu phần (g)',
  'mealTime': 'Giờ ăn',
  'amount': 'Lượng',

  'healthTitle': 'Nhật ký sức khỏe',
  'healthType': 'Loại ghi chép',
  'healthIllness': 'Bệnh',
  'healthMedication': 'Thuốc',
  'healthCheckupType': 'Khám',
  'healthOther': 'Khác',
  'medicationName': 'Tên thuốc',
  'symptoms': 'Triệu chứng',

  'groomingTitle': 'Chăm sóc',
  'groomingBath': 'Tắm',
  'groomingNailTrim': 'Cắt móng',
  'groomingHaircut': 'Cắt lông',
  'groomingBrush': 'Chải lông',
  'groomingOther': 'Khác',
  'nextGrooming': 'Lần chăm sóc tiếp',

  'statisticsTitle': 'Thống kê',
  'weightChart': 'Biểu đồ cân nặng',
  'careSchedule': 'Lịch chăm sóc',
  'statsProLocked': 'Biểu đồ nâng cao bị khóa. Mở khóa tại Cửa hàng.',
  'week': 'Tuần',
  'month': 'Tháng',
  'year': 'Năm',
  'all': 'Tất cả',

  'vaccineTitle': 'Lịch tiêm',
  'vaccineReminder': 'Nhắc tiêm',
  'vaccineDue': 'Đến hạn tiêm',
  'vaccineDone': 'Đã tiêm',
  'nextVaccine': 'Mũi tiêm tiếp',
  'vaccineReminderLocked': 'Nhắc tiêm bị khóa. Mở khóa tại Cửa hàng.',
  'note': 'Ghi chú',
  'notes': 'Ghi chú',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'delete': 'Xóa',
  'search': 'Tìm theo ngày...',
  'noLogs': 'Chưa có hoạt động',
  'addFirstLog': 'Ghi hoạt động đầu tiên',
  'itsTime': 'Đến giờ rồi!',
  'multiPetLocked': 'Nhiều thú cưng bị khóa. Mở khóa tại Cửa hàng.',

  'tipsTitle': 'Mẹo chăm sóc thú cưng',
  'tip1Title': 'Ăn uống đều đặn',
  'tip1Body': 'Duy trì lịch ăn cố định. Theo dõi khẩu phần để giữ cân nặng khỏe mạnh.',
  'tip2Title': 'Tiêm phòng',
  'tip2Body': 'Tuân theo lịch tiêm của bác sĩ thú y để bảo vệ thú cưng.',
  'tip3Title': 'Chăm sóc thường xuyên',
  'tip3Body': 'Tắm, cắt móng và chải lông giúp thú cưng sạch sẽ, khỏe mạnh.',
  'tip4Title': 'Theo dõi cân nặng',
  'tip4Body': 'Ghi cân nặng theo thời gian để phát hiện sớm vấn đề sức khỏe.',
  'tip5Title': 'Nhật ký sức khỏe',
  'tip5Body': 'Ghi bệnh và thuốc đã dùng để chia sẻ với bác sĩ thú y.',

  'onboardingTitle': 'Chào mừng đến PetCare',
  'onboardingSubtitle': 'Giúp bạn chăm sóc thú cưng tốt hơn',
  'onboardingStep1': 'Theo dõi ăn uống, sức khỏe & chăm sóc hàng ngày',
  'onboardingStep2': 'Biểu đồ cân nặng & lịch tiêm',
  'onboardingStep3': 'Kiếm sao để mở khóa giao diện & tính năng',
  'getStarted': 'Bắt đầu',
  'skip': 'Bỏ qua',
  'next': 'Tiếp',

  'shopTitle': 'Cửa hàng',
  'shopSubtitle': 'Kiếm hoặc mua sao để mở khóa giao diện & tính năng',
  'yourWallet': 'Ví sao của bạn',
  'coinsLabel': 'sao',
  'buyCoins': 'Mua sao',
  'earnCoins': 'Kiếm sao',
  'dailyRewardDone': 'Đã nhận hôm nay',
  'earnStepDaily': 'Đăng nhập hàng ngày',
  'claimDailyButton': 'Nhận',
  'earnStepLogActivity': 'Ghi hoạt động',
  'earnStepLogActivityDesc': '+5 sao mỗi lần ghi',
  'earnStepCare': 'Hoàn thành chăm sóc',
  'earnStepCareDesc': '+8 sao mỗi lần chăm sóc',
  'earnStepStreak': 'Chuỗi ngày',
  'earnStepStreakDesc': '+15 sao cho chuỗi ngày',
  'earnStepBuy': 'Mua thêm sao',
  'buyWithGooglePlay': 'Google Play',
  'shopBrowse': 'Khám phá',
  'shopMenuAll': 'Tất cả',
  'shopMenuPremium': 'Cao cấp',
  'shopMenuThemes': 'Giao diện',
  'shopMenuCards': 'Hình nền',
  'shopMenuSkins': 'Skin thẻ',
  'shopMenuFeatures': 'Tính năng',
  'shopEmptyCategory': 'Chưa có gì ở đây',
  'shopRemoveAds': 'Bỏ quảng cáo',
  'shopRemoveAdsDesc': 'Trải nghiệm không quảng cáo',
  'shopThemeForest': 'Rừng xanh',
  'shopThemeForestDesc': 'Tông xanh tươi mát',
  'shopThemeSunset': 'Hoàng hôn',
  'shopThemeSunsetDesc': 'Cam ấm áp',
  'shopThemeOcean': 'Đại dương',
  'shopThemeOceanDesc': 'Tông xanh dương',
  'shopThemeCandy': 'Kẹo ngọt',
  'shopThemeCandyDesc': 'Pastel dễ thương',
  'shopBgPaws': 'Dấu chân',
  'shopBgPawsDesc': 'Họa tiết chân thú',
  'shopBgStars': 'Đêm sao',
  'shopBgStarsDesc': 'Lấp lánh',
  'shopBgGrass': 'Cỏ xanh',
  'shopBgGrassDesc': 'Đồng cỏ xanh',
  'shopBgBubbles': 'Bong bóng',
  'shopBgBubblesDesc': 'Vui nhộn',
  'shopSkinSoft': 'Mềm mại',
  'shopSkinSoftDesc': 'Bo góc lớn hơn',
  'shopSkinCute': 'Dễ thương',
  'shopSkinCuteDesc': 'Viền cam pastel',
  'shopSkinPlayful': 'Vui tươi',
  'shopSkinPlayfulDesc': 'Hiệu ứng kính mờ',
  'shopFeatMultiPet': 'Nhiều thú cưng',
  'shopFeatMultiPetDesc': 'Theo dõi tới 10 thú cưng',
  'shopFeatExport': 'Xuất dữ liệu',
  'shopFeatExportDesc': 'Xuất nhật ký ra file',
  'shopFeatStatsPro': 'Stats Pro',
  'shopFeatStatsProDesc': 'Biểu đồ cân nặng nâng cao',
  'shopFeatVaccineReminder': 'Nhắc tiêm',
  'shopFeatVaccineReminderDesc': 'Thông báo đẩy nhắc tiêm',
  'purchaseSuccess': 'Mua thành công!',
  'purchaseFailed': 'Mua thất bại',
  'insufficientCoins': 'Không đủ sao',
  'alreadyOwned': 'Đã sở hữu',
  'applied': 'Đã áp dụng',
  'apply': 'Áp dụng',
  'resetDefault': 'Mặc định',
  'resetToDefault': 'Đặt lại mặc định',
  'owned': 'Đã mua',
  'active': 'Đang dùng',
  'removeAdsIap': 'Mua qua Google Play',
  'openingBilling': 'Đang mở thanh toán...',
  'coinsAdded': 'Đã thêm sao!',
  'removeAdsUnlocked': 'Đã bỏ quảng cáo!',
  'dailyRewardClaimed': 'Đã nhận thưởng hàng ngày!',
  'logActivityRewardEarned': '+5 sao khi ghi nhật ký!',
  'careRewardEarned': '+8 sao khi chăm sóc!',
  'streakRewardEarned': '+15 sao cho chuỗi ngày!',
  'configTimeout': 'Hết thời gian. Dùng bản đã lưu.',
  'configNetworkError': 'Lỗi mạng. Dùng bản đã lưu.',

  'settings': 'Cài đặt',
  'language': 'Ngôn ngữ',
  'darkMode': 'Giao diện tối',
  'exportData': 'Xuất dữ liệu',
  'exportLocked': 'Xuất dữ liệu bị khóa. Mở khóa tại Cửa hàng.',
  'privacyPolicy': 'Chính sách riêng tư',
  'about': 'Giới thiệu',
  'version': 'Phiên bản',
  'privacyPolicyBody':
      'PetCare lưu dữ liệu thú cưng và cài đặt cục bộ trên thiết bị. Chúng tôi không thu thập dữ liệu cá nhân trên máy chủ. Mua trong ứng dụng qua Google Play. JSON cấu hình từ api2.blwsmartware.net để quản lý IAP — không gửi dữ liệu cá nhân. Liên hệ: support@petcare.app',
};
