const Map<String, String> appStringsEn = {
  'appName': 'PetCare',
  'appTagline': 'Love Your Pets Every Day.',
  'splashLoading': 'Loading...',

  'navHome': 'Home',
  'navTips': 'Tips',
  'navLogs': 'Stats',
  'navTimeline': 'Timeline',
  'navMore': 'More',
  'navShop': 'Shop',
  'navSettings': 'Settings',

  'tabPets': 'Pets',
  'tabRoutines': 'Routines',
  'tabFamily': 'Family',
  'tabJournals': 'Journals',

  'addPet': 'Add pet',
  'editPet': 'Edit pet',
  'petProfile': 'Pet profile',
  'petName': 'Pet name',
  'species': 'Species',
  'speciesDog': 'Dog',
  'speciesCat': 'Cat',
  'speciesOther': 'Other',
  'breed': 'Breed',
  'birthDate': 'Birth date',
  'furColor': 'Fur color',
  'gender': 'Gender',
  'genderMale': 'Male',
  'genderFemale': 'Female',
  'genderUnknown': 'Unknown',
  'changePhoto': 'Change photo',
  'addPhoto': 'Add photo',
  'tapToAddPhoto': 'Tap to add a photo',
  'chooseGallery': 'Choose from gallery',
  'takePhoto': 'Take a photo',
  'todaySummary': 'Today',
  'summaryFeeding': '{count} feedings',
  'summaryGrooming': '{count} grooming',
  'summaryHealth': '{count} health logs',
  'summaryTotal': '{count} activities',
  'lastCare': 'Last care',
  'myPets': 'My Pets',
  'homeGreeting': 'Hi {name},',
  'homeSubtitlePrefix': "Let's take care of your ",
  'homeSubtitleHighlight': 'cutie pets!',
  'nutrition': 'Nutrition',
  'consult': 'Consult',
  'healthCheckup': 'Health Checkup',
  'reminderHealthCheckup': 'Health Checkup',
  'petDetails': 'Pet Details',
  'onboardingHeadlinePart1': 'Helping',
  'onboardingHeadlineYou': 'you',
  'onboardingHeadlinePart2': 'to take good care of your',
  'onboardingHeadlinePet': 'Pet',
  'onboardingCaption': 'All pets deserve some care and love!',
  'weightLabel': 'Weight',
  'noWeightYet': 'No weight recorded',

  'feeding': 'Feeding',
  'vaccine': 'Vaccine',
  'health': 'Health',
  'grooming': 'Grooming',
  'statistics': 'Statistics',
  'weight': 'Weight (kg)',
  'profile': 'Profile',
  'timeline': 'Timeline',

  'feedingTitle': 'Log feeding',
  'feedingType': 'Food type',
  'feedingDry': 'Dry food',
  'feedingWet': 'Wet food',
  'feedingRaw': 'Raw food',
  'feedingTreat': 'Treats',
  'feedingHomemade': 'Homemade',
  'portion': 'Portion (g)',
  'mealTime': 'Meal time',
  'amount': 'Amount',

  'healthTitle': 'Health journal',
  'healthType': 'Record type',
  'healthIllness': 'Illness',
  'healthMedication': 'Medication',
  'healthCheckupType': 'Checkup',
  'healthOther': 'Other',
  'medicationName': 'Medication name',
  'symptoms': 'Symptoms',

  'groomingTitle': 'Grooming',
  'groomingBath': 'Bath',
  'groomingNailTrim': 'Nail trim',
  'groomingHaircut': 'Haircut',
  'groomingBrush': 'Brush',
  'groomingOther': 'Other',
  'nextGrooming': 'Next grooming',

  'statisticsTitle': 'Statistics',
  'weightChart': 'Weight chart',
  'careSchedule': 'Care schedule',
  'statsProLocked': 'Advanced charts locked. Unlock in Shop.',
  'week': 'Week',
  'month': 'Month',
  'year': 'Year',
  'all': 'All',

  'vaccineTitle': 'Vaccine schedule',
  'vaccineReminder': 'Vaccine reminder',
  'vaccineDue': 'Due for vaccine',
  'vaccineDone': 'Completed',
  'nextVaccine': 'Next vaccine',
  'vaccineReminderLocked': 'Vaccine reminders locked. Unlock in Shop.',
  'note': 'Note',
  'notes': 'Notes',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'search': 'Search by date...',
  'noLogs': 'No activities yet',
  'addFirstLog': 'Log your first activity',
  'itsTime': "It's time!",
  'multiPetLocked': 'Multiple pets locked. Unlock in Shop.',

  'tipsTitle': 'Pet care tips',
  'tip1Title': 'Regular feeding',
  'tip1Body': 'Keep a consistent feeding schedule. Track portions to maintain healthy weight.',
  'tip2Title': 'Vaccinations',
  'tip2Body': 'Follow your vet\'s vaccine schedule to protect your pet from diseases.',
  'tip3Title': 'Grooming routine',
  'tip3Body': 'Regular baths, nail trims, and brushing keep your pet clean and healthy.',
  'tip4Title': 'Weight monitoring',
  'tip4Body': 'Track weight over time to catch health issues early.',
  'tip5Title': 'Health journal',
  'tip5Body': 'Record illnesses and medications to share with your veterinarian.',

  'onboardingTitle': 'Welcome to PetCare',
  'onboardingSubtitle': 'Helping you take good care of your pet',
  'onboardingStep1': 'Track feeding, health & grooming daily',
  'onboardingStep2': 'Weight charts & vaccine schedule',
  'onboardingStep3': 'Earn stars to unlock themes & features',
  'getStarted': 'Get started',
  'skip': 'Skip',
  'next': 'Next',

  'shopTitle': 'Shop',
  'shopSubtitle': 'Earn or buy stars to unlock themes & features',
  'yourWallet': 'Your star wallet',
  'coinsLabel': 'stars',
  'buyCoins': 'Buy stars',
  'earnCoins': 'Earn stars',
  'dailyRewardDone': 'Claimed today',
  'earnStepDaily': 'Daily login',
  'claimDailyButton': 'Claim',
  'earnStepLogActivity': 'Log activity',
  'earnStepLogActivityDesc': '+5 stars per log',
  'earnStepCare': 'Complete care task',
  'earnStepCareDesc': '+8 stars per care task',
  'earnStepStreak': 'Day streak',
  'earnStepStreakDesc': '+15 stars for streak',
  'earnStepBuy': 'Buy more stars',
  'buyWithGooglePlay': 'Google Play',
  'shopBrowse': 'Browse',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuCards': 'Backgrounds',
  'shopMenuSkins': 'Skins',
  'shopMenuFeatures': 'Features',
  'shopEmptyCategory': 'Nothing here yet',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Ad-free experience',
  'shopThemeForest': 'Forest',
  'shopThemeForestDesc': 'Fresh green nature',
  'shopThemeSunset': 'Sunset',
  'shopThemeSunsetDesc': 'Warm orange glow',
  'shopThemeOcean': 'Ocean',
  'shopThemeOceanDesc': 'Cool blue tones',
  'shopThemeCandy': 'Candy',
  'shopThemeCandyDesc': 'Sweet pastel mix',
  'shopBgPaws': 'Paw prints',
  'shopBgPawsDesc': 'Cute paw pattern',
  'shopBgStars': 'Starry night',
  'shopBgStarsDesc': 'Sparkling stars',
  'shopBgGrass': 'Grass field',
  'shopBgGrassDesc': 'Green meadow',
  'shopBgBubbles': 'Bubbles',
  'shopBgBubblesDesc': 'Playful bubbles',
  'shopSkinSoft': 'Soft',
  'shopSkinSoftDesc': 'Extra rounded corners',
  'shopSkinCute': 'Cute',
  'shopSkinCuteDesc': 'Orange border style',
  'shopSkinPlayful': 'Playful',
  'shopSkinPlayfulDesc': 'Glass effect cards',
  'shopFeatMultiPet': 'Multi-pet',
  'shopFeatMultiPetDesc': 'Track up to 10 pets',
  'shopFeatExport': 'Export data',
  'shopFeatExportDesc': 'Export logs to file',
  'shopFeatStatsPro': 'Stats Pro',
  'shopFeatStatsProDesc': 'Advanced weight charts',
  'shopFeatVaccineReminder': 'Vaccine reminders',
  'shopFeatVaccineReminderDesc': 'Push notification reminders',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed',
  'insufficientCoins': 'Not enough stars',
  'alreadyOwned': 'Already owned',
  'applied': 'Applied',
  'apply': 'Apply',
  'resetDefault': 'Default',
  'resetToDefault': 'Reset to default',
  'owned': 'Owned',
  'active': 'Active',
  'removeAdsIap': 'Buy via Google Play',
  'openingBilling': 'Opening billing...',
  'coinsAdded': 'Stars added!',
  'removeAdsUnlocked': 'Ads removed!',
  'dailyRewardClaimed': 'Daily reward claimed!',
  'logActivityRewardEarned': '+5 stars for logging!',
  'careRewardEarned': '+8 stars for care task!',
  'streakRewardEarned': '+15 stars for streak!',
  'configTimeout': 'Config timeout. Using cached version.',
  'configNetworkError': 'Network error. Using cached version.',

  'settings': 'Settings',
  'language': 'Language',
  'darkMode': 'Dark mode',
  'exportData': 'Export data',
  'exportLocked': 'Export locked. Unlock in Shop.',
  'privacyPolicy': 'Privacy policy',
  'about': 'About',
  'version': 'Version',
  'privacyPolicyBody':
      'PetCare stores pet data and settings locally on your device. We do not collect personal data on our servers. In-app purchases are processed by Google Play. A remote config JSON is fetched from api2.blwsmartware.net to manage IAP availability — no personal data is sent. Contact: support@petcare.app',
};
